"""add_archive_and_supplier_fields

Revision ID: e84098e5ded7
Revises: 1f0dee1f49bd
Create Date: 2026-07-12 17:54:28.493775

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e84098e5ded7"
down_revision = "1f0dee1f49bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "is_archived", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "locations",
        sa.Column(
            "is_archived", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column("suppliers", sa.Column("customer_number", sa.String(), nullable=True))
    op.add_column("suppliers", sa.Column("comment", sa.String(), nullable=True))
    op.add_column(
        "suppliers",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.add_column(
        "suppliers",
        sa.Column(
            "is_archived", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suppliers", "is_archived")
    op.drop_column("suppliers", "is_active")
    op.drop_column("suppliers", "comment")
    op.drop_column("suppliers", "customer_number")
    op.drop_column("locations", "is_archived")
    op.drop_column("categories", "is_archived")
    # ### end Alembic commands ###
